services:
  booking:
    image: booking-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5559:8080"
    volumes:
      #- c:/data/website/booking:/app/Data/Images
      - /data/website/images:/app/Data/Images